#!/usr/bin/env python
"""
Rewriting this: https://raw.githubusercontent.com/freebsd/freebsd-src/main/usr.sbin/freebsd-update/freebsd-update.sh
In Python to see if it speeds up disc actions like inspecting system...
"""
import sys

class Configuration:
  def __init__(self, saved=False, value='iii', option=None):
    self.list = []
    self.saved = False if not saved else saved
    self.value = 'i' if not value else value
    self.option = option if not option else option

  def init(self):
    self.list.extend([Configuration(False, 'ii', i) for i in "KEYPRINT WORKDIR SERVERNAME MAILTO ALLOWADD ALLOWDELETE KEEPMODIFIEDMETADATA COMPONENTS IGNOREPATHS UPDATEIFUNMODIFIED BASEDIR VERBOSELEVEL TARGETRELEASE STRICTCOMPONENTS MERGECHANGES IDSIGNOREPATHS BACKUPKERNEL BACKUPKERNELDIR BACKUPKERNELSYMBOLFILES".split(' ')])
  def null(self):
    self.list = [Configuration(x.saved, '', x.option) for x in self.list]
  def save(self):
    self.list = [Configuration(True, x.value, x.option) for x in self.list]
  def get(self):
    return self.list
  def getitem(self):
    return self.saved, self.value, self.option
  def print(self, cfg):
    [print(x.getitem()) for x in cfg.get()]

def usage():
  print('usage: fu [options] command ...\n')
  print('Options:')
  print('  -b basedir   -- Operate on a system mounted at basedir')
  print('                  (default: /)')
  print('  -d workdir   -- Store working files in workdir')
  print('                  (default: /var/db/freebsd-update/)')
  print('  -f conffile  -- Read configuration options from conffile')
  print('                  (default: /etc/freebsd-update.conf)')
  print('  -F           -- Force a fetch operation to proceed in the')
  print('                  case of an unfinished upgrade')
  print('  -j jail      -- Operate on the given jail specified by jid or name')
  print('  -k KEY       -- Trust an RSA key with SHA256 hash of KEY')
  print('  -r release   -- Target for upgrade (e.g., 13.2-RELEASE)')
  print('  -s server    -- Server from which to fetch updates')
  print('                  (default: update.FreeBSD.org)')
  print('  -t address   -- Mail output of cron command, if any, to address')
  print('                  (default: root)')
  print('  --not-running-from-cron')
  print('               -- Run without a tty, for use by automated tools')
  print('  --currently-running release')
  print('               -- Update as if currently running this release')
  print('Commands:')
  print('  fetch        -- Fetch updates from server')
  print('  cron         -- Sleep rand(3600) seconds, fetch updates, and send an')
  print('                  email if updates were found')
  print('  upgrade      -- Fetch upgrades to FreeBSD version specified via -r option')
  print('  updatesready -- Check if there are fetched updates ready to install')
  print('  install      -- Install downloaded updates or upgrades')
  print('  rollback     -- Uninstall most recently installed updates')
  print('  IDS          -- Compare the system against an index of "known good" files')
  print('  showconfig   -- Show configuration')
  exit()


if __name__ == '__main__':
  #if len(sys.argv) < 2:
  #  usage()
  cfg = Configuration()
  print("-----")
  cfg.init()
  cfg.print(cfg)
  print("-----------")
  cfg.null()
  cfg.print(cfg)
  print("-----------")
  cfg.save()
  cfg.print(cfg)

